from pathlib import Path

app = Path('uniview_camera_bridge/app.py')
text = app.read_text()

# Add capability parser near build_camera_clients.
marker = '''def build_camera_clients(options: dict[str, Any]) -> dict[int, UniviewCamera]:\n'''
helper = '''def ptz_capability_flags(options_data: dict[str, Any]) -> dict[str, bool]:\n    """Normalise ONVIF PTZ spaces into capability flags used by the bridge.\n\n    PTZ is a collection of independent capabilities. A camera may expose zoom\n    without pan/tilt (for example a motorised varifocal camera), so discovery\n    must not depend on a manually-declared full-PTZ flag.\n    """\n    spaces = options_data.get("spaces") if isinstance(options_data, dict) else {}\n    spaces = spaces if isinstance(spaces, dict) else {}\n    return {\n        "ptz_zoom_absolute": bool(spaces.get("AbsoluteZoomPositionSpace")),\n        "ptz_zoom_relative": bool(spaces.get("RelativeZoomTranslationSpace")),\n        "ptz_zoom_continuous": bool(spaces.get("ContinuousZoomVelocitySpace")),\n        "ptz_pan_tilt_absolute": bool(spaces.get("AbsolutePanTiltPositionSpace")),\n        "ptz_pan_tilt_relative": bool(spaces.get("RelativePanTiltTranslationSpace")),\n        "ptz_pan_tilt_continuous": bool(spaces.get("ContinuousPanTiltVelocitySpace")),\n    }\n\n\n'''
if helper not in text:
    if marker not in text:
        raise SystemExit('build_camera_clients marker missing')
    text = text.replace(marker, helper + marker, 1)

# Probe PTZ/zoom capabilities for every enabled camera, not just ptz_enabled cameras.
old_probe = '''    for camera_def in camera_defs:\n        source_id = int(camera_def.get("source_id", 0))\n        if not bool(camera_def.get("ptz_enabled", False)):\n            continue\n        client = camera_clients.get(source_id)\n        if client is None:\n            continue\n        try:\n            ptz_options = client.get_ptz_configuration_options()\n            camera_caps.setdefault(source_id, {})["ptz_options"] = ptz_options\n            logging.info("D%d ONVIF PTZ configuration options: %s", source_id, json.dumps(ptz_options, sort_keys=True))\n        except Exception as exc:\n            logging.warning("D%d ONVIF PTZ configuration-options probe failed: %s", source_id, exc)\n        try:\n            position = client.get_zoom()\n            camera_caps.setdefault(source_id, {})["ptz_zoom"] = True\n            camera_caps[source_id]["zoom_percent"] = round(position * 100.0, 1)\n            logging.info("D%d ONVIF zoom position: %.6f (%.1f%%)", source_id, position, position * 100.0)\n        except Exception as exc:\n            camera_caps.setdefault(source_id, {})["ptz_zoom"] = False\n            logging.warning("D%d ONVIF zoom-position probe failed: %s", source_id, exc)\n'''
new_probe = '''    for camera_def in camera_defs:\n        source_id = int(camera_def.get("source_id", 0))\n        client = camera_clients.get(source_id)\n        if client is None:\n            continue\n        caps = camera_caps.setdefault(source_id, {})\n        try:\n            ptz_options = client.get_ptz_configuration_options()\n            caps["ptz_options"] = ptz_options\n            caps.update(ptz_capability_flags(ptz_options))\n            logging.info("D%d ONVIF PTZ capabilities: %s", source_id, json.dumps({\n                key: value for key, value in caps.items() if key.startswith("ptz_") and key != "ptz_options"\n            }, sort_keys=True))\n        except Exception as exc:\n            logging.debug("D%d ONVIF PTZ configuration-options probe unavailable: %s", source_id, exc)\n        if caps.get("ptz_zoom_absolute"):\n            try:\n                position = client.get_zoom()\n                caps["ptz_zoom"] = True\n                caps["zoom_percent"] = round(position * 100.0, 1)\n                logging.info("D%d ONVIF absolute zoom: available, position %.6f (%.1f%%)", source_id, position, position * 100.0)\n            except Exception as exc:\n                caps["ptz_zoom"] = False\n                logging.warning("D%d advertises absolute zoom but GetStatus failed: %s", source_id, exc)\n        else:\n            caps["ptz_zoom"] = False\n'''
if old_probe not in text:
    raise SystemExit('startup PTZ probe block not found')
text = text.replace(old_probe, new_probe, 1)

# Add active polling state.
old_poll = '''    ptz_zoom_poll = max(0.2, float(options.get("ptz_zoom_poll_seconds", 1.0)))\n    next_ptz_zoom_poll: dict[int, float] = {\n        source_id: 0.0 for source_id, caps in camera_caps.items() if caps.get("ptz_zoom")\n    }\n'''
new_poll = '''    ptz_zoom_poll = max(0.2, float(options.get("ptz_zoom_poll_seconds", 1.0)))\n    ptz_zoom_active_poll = max(0.1, float(options.get("ptz_zoom_active_poll_seconds", 0.2)))\n    ptz_zoom_tolerance = max(0.05, float(options.get("ptz_zoom_target_tolerance_percent", 0.5)))\n    ptz_zoom_targets: dict[int, float] = {}\n    next_ptz_zoom_poll: dict[int, float] = {\n        source_id: 0.0 for source_id, caps in camera_caps.items() if caps.get("ptz_zoom")\n    }\n'''
if old_poll not in text:
    raise SystemExit('zoom polling init not found')
text = text.replace(old_poll, new_poll, 1)

# Make generic absolute zoom non-blocking and independent of manual full-PTZ policy.
old_zoom = '''                        elif action == "camera_zoom_set":\n                            camera_def = next((item for item in camera_defs if int(item.get("source_id", 0)) == source_id), None)\n                            if not camera_def or not bool(camera_def.get("ptz_enabled", False)) or not camera_caps.get(source_id, {}).get("ptz_zoom"):\n                                logging.warning("D%d does not expose absolute bridge zoom control", source_id)\n                            else:\n                                percent = float(command.get("percent"))\n                                if not 0.0 <= percent <= 100.0:\n                                    raise ValueError(f"D{source_id} zoom percentage must be between 0 and 100, got {percent}")\n                                client.set_zoom(percent / 100.0)\n                                time.sleep(0.15)\n                                position = client.get_zoom()\n                                camera_caps[source_id]["zoom_percent"] = round(position * 100.0, 1)\n                                mqtt.publish_camera_controls(source_id, {"zoom_percent": camera_caps[source_id]["zoom_percent"]})\n                                next_ptz_zoom_poll[source_id] = time.monotonic() + ptz_zoom_poll\n                                logging.info("D%d absolute zoom -> %.1f%% (reported %.1f%%)", source_id, percent, position * 100.0)\n'''
new_zoom = '''                        elif action == "camera_zoom_set":\n                            caps = camera_caps.get(source_id, {})\n                            if not caps.get("ptz_zoom") or not caps.get("ptz_zoom_absolute"):\n                                logging.warning("D%d does not expose ONVIF absolute zoom control", source_id)\n                            else:\n                                percent = float(command.get("percent"))\n                                if not 0.0 <= percent <= 100.0:\n                                    raise ValueError(f"D{source_id} zoom percentage must be between 0 and 100, got {percent}")\n                                client.set_zoom(percent / 100.0)\n                                # AbsoluteMove is intentionally non-blocking. The camera may\n                                # accept a newer target while still travelling; position is\n                                # observed independently by the fast active-motion poll.\n                                ptz_zoom_targets[source_id] = percent\n                                next_ptz_zoom_poll[source_id] = time.monotonic()\n                                logging.info("D%d absolute zoom target -> %.1f%%", source_id, percent)\n'''
if old_zoom not in text:
    raise SystemExit('camera_zoom_set block not found')
text = text.replace(old_zoom, new_zoom, 1)

# Make continuous PTZ capability-driven per requested axis. ptz_enabled remains an optional policy gate
# for pan/tilt, but zoom-only cameras do not need it.
old_ptz_gate = '''                        elif action == "camera_ptz":\n                            camera_def = next((item for item in camera_defs if int(item.get("source_id", 0)) == source_id), None)\n                            if not camera_def or not bool(camera_def.get("ptz_enabled", False)):\n                                logging.warning("D%d does not have bridge PTZ control enabled", source_id)\n                            elif bool(command.get("stop", False)):\n                                client.stop_move()\n                                ptz_stop_deadlines.pop(source_id, None)\n                                logging.debug("D%d PTZ stop", source_id)\n                            else:\n                                pan = max(-1.0, min(1.0, float(command.get("pan", 0.0))))\n                                tilt = max(-1.0, min(1.0, float(command.get("tilt", 0.0))))\n                                zoom = max(-1.0, min(1.0, float(command.get("zoom", 0.0))))\n                                client.continuous_move(pan=pan, tilt=tilt, zoom=zoom)\n                                timeout = float(options.get("ptz_safety_timeout_seconds", 3.0))\n                                ptz_stop_deadlines[source_id] = time.monotonic() + timeout\n                                logging.debug("D%d PTZ velocity pan=%.3f tilt=%.3f zoom=%.3f", source_id, pan, tilt, zoom)\n'''
new_ptz_gate = '''                        elif action == "camera_ptz":\n                            camera_def = next((item for item in camera_defs if int(item.get("source_id", 0)) == source_id), {})\n                            caps = camera_caps.get(source_id, {})\n                            if bool(command.get("stop", False)):\n                                if caps.get("ptz_zoom_continuous") or caps.get("ptz_pan_tilt_continuous"):\n                                    client.stop_move()\n                                ptz_stop_deadlines.pop(source_id, None)\n                                logging.debug("D%d PTZ stop", source_id)\n                            else:\n                                pan = max(-1.0, min(1.0, float(command.get("pan", 0.0))))\n                                tilt = max(-1.0, min(1.0, float(command.get("tilt", 0.0))))\n                                zoom = max(-1.0, min(1.0, float(command.get("zoom", 0.0))))\n                                wants_pan_tilt = abs(pan) >= 1e-6 or abs(tilt) >= 1e-6\n                                wants_zoom = abs(zoom) >= 1e-6\n                                pan_tilt_allowed = bool(camera_def.get("ptz_enabled", False)) and caps.get("ptz_pan_tilt_continuous")\n                                zoom_allowed = caps.get("ptz_zoom_continuous")\n                                if wants_pan_tilt and not pan_tilt_allowed:\n                                    logging.warning("D%d does not expose enabled continuous pan/tilt", source_id)\n                                elif wants_zoom and not zoom_allowed:\n                                    logging.warning("D%d does not expose continuous zoom", source_id)\n                                elif not wants_pan_tilt and not wants_zoom:\n                                    client.stop_move()\n                                    ptz_stop_deadlines.pop(source_id, None)\n                                else:\n                                    client.continuous_move(pan=pan, tilt=tilt, zoom=zoom)\n                                    timeout = float(options.get("ptz_safety_timeout_seconds", 3.0))\n                                    ptz_stop_deadlines[source_id] = time.monotonic() + timeout\n                                    logging.debug("D%d PTZ velocity pan=%.3f tilt=%.3f zoom=%.3f", source_id, pan, tilt, zoom)\n'''
if old_ptz_gate not in text:
    raise SystemExit('camera_ptz block not found')
text = text.replace(old_ptz_gate, new_ptz_gate, 1)

# Active/idle poll scheduling.
old_poll_loop = '''                    try:\n                        position = client.get_zoom()\n                        camera_caps[source_id]["zoom_percent"] = round(position * 100.0, 1)\n                        mqtt.publish_camera_controls(source_id, {"zoom_percent": camera_caps[source_id]["zoom_percent"]})\n                    except Exception as exc:\n                        logging.debug("D%d zoom-position poll failed: %s", source_id, exc)\n                    next_ptz_zoom_poll[source_id] = now_mono + ptz_zoom_poll\n'''
new_poll_loop = '''                    try:\n                        position = client.get_zoom()\n                        reported = round(position * 100.0, 1)\n                        camera_caps[source_id]["zoom_percent"] = reported\n                        mqtt.publish_camera_controls(source_id, {"zoom_percent": reported})\n                        target = ptz_zoom_targets.get(source_id)\n                        if target is not None and abs(reported - target) <= ptz_zoom_tolerance:\n                            ptz_zoom_targets.pop(source_id, None)\n                            target = None\n                        next_ptz_zoom_poll[source_id] = now_mono + (ptz_zoom_active_poll if target is not None else ptz_zoom_poll)\n                    except Exception as exc:\n                        logging.debug("D%d zoom-position poll failed: %s", source_id, exc)\n                        next_ptz_zoom_poll[source_id] = now_mono + ptz_zoom_poll\n'''
if old_poll_loop not in text:
    raise SystemExit('zoom poll loop not found')
text = text.replace(old_poll_loop, new_poll_loop, 1)

# Legacy rear zoom path: remove the blocking settle loop. It remains only as a compatibility path.
old_rear_wait = '''    rear_camera.set_zoom(target)\n    tolerance = float(options.get("rear_zoom_preset_tolerance", 0.006))\n    deadline = time.monotonic() + float(options.get("rear_zoom_move_timeout_seconds", 8.0))\n    position = current\n    while time.monotonic() < deadline:\n        time.sleep(0.20)\n        position = rear_camera.get_zoom()\n        if abs(position - target) <= tolerance:\n            break\n    else:\n        logging.warning(\n            "Rear camera zoom did not settle at %.6f within timeout; reported %.6f",\n            target,\n            position,\n        )\n    return rear_zoom_status(rear_camera, options)\n'''
new_rear_wait = '''    rear_camera.set_zoom(target)\n    # Legacy compatibility path only: do not wait for the move to finish.\n    # New installations should use the capability-discovered camera/Dn/zoom/set path.\n    status = rear_zoom_status(rear_camera, options)\n    status["target_percent"] = round(target * 100.0, 1)\n    return status\n'''
if old_rear_wait not in text:
    raise SystemExit('legacy rear blocking loop not found')
text = text.replace(old_rear_wait, new_rear_wait, 1)

# Runtime version string.
text = text.replace('options["addon_version"] = "1.5.13"', 'options["addon_version"] = "1.6.2"')
text = text.replace('UNIVIEW CAMERA BRIDGE STARTING - version 1.6.1', 'UNIVIEW CAMERA BRIDGE STARTING - version 1.6.2')
app.write_text(text)

# Add config knobs and bump version.
cfg = Path('uniview_camera_bridge/config.yaml')
c = cfg.read_text()
c = c.replace('version: 1.6.1', 'version: 1.6.2', 1)
c = c.replace('  ptz_zoom_poll_seconds: 1.0\n', '  ptz_zoom_poll_seconds: 1.0\n  ptz_zoom_active_poll_seconds: 0.2\n  ptz_zoom_target_tolerance_percent: 0.5\n', 1)
c = c.replace('  ptz_zoom_poll_seconds: float(0.2,60.0)?\n', '  ptz_zoom_poll_seconds: float(0.2,60.0)?\n  ptz_zoom_active_poll_seconds: float(0.1,5.0)?\n  ptz_zoom_target_tolerance_percent: float(0.05,5.0)?\n', 1)
cfg.write_text(c)

# Changelog entry.
chg = Path('uniview_camera_bridge/CHANGELOG.md')
ch = chg.read_text()
entry = '''## 1.6.2\n\n- Make ONVIF PTZ/zoom discovery capability-driven for every enabled camera instead of requiring a hard-coded full-PTZ flag.\n- Treat absolute, relative and continuous zoom plus pan/tilt spaces as independent capabilities, allowing zoom-only motorised cameras to use the generic camera control path.\n- Make absolute zoom commands non-blocking so a newer target can replace an in-flight target.\n- Poll reported zoom position at 0.2 s while a target is outstanding, then return to the normal idle poll interval.\n- Keep the legacy `rear_zoom_*` path only as a non-blocking compatibility path; new control should use `camera/Dn/zoom/set`.\n\n'''
if not ch.startswith('## 1.6.2'):
    chg.write_text(entry + ch)
