from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "uniview_camera_bridge"
U = ROOT / "uniview.py"
A = ROOT / "app.py"
C = ROOT / "config.yaml"
CH = ROOT / "CHANGELOG.md"


def repl(path: Path, old: str, new: str) -> None:
    text = path.read_text(encoding="utf-8")
    if old not in text:
        raise RuntimeError(f"expected text not found in {path}")
    path.write_text(text.replace(old, new, 1), encoding="utf-8")


old = '''    def get_day_night_mode(self, channel: int, private: bool = False) -> str:\n        # The native D2 UI writes to the Private/Exposure endpoint, but that\n        # endpoint is not a reliable GET endpoint. Read current state from the\n        # ordinary Exposure resource and use Private/Exposure only for writes.\n        exposure = self.get_exposure(channel)\n        day_night = exposure.get("DayNight") or {}\n        raw_mode = day_night.get("Mode")\n        if raw_mode is None:\n            return "Unknown"\n        mode = int(raw_mode)\n        return {0: "Auto", 1: "Day", 2: "Night"}.get(mode, f"Unknown ({mode})")\n\n'''
new = old + """    def get_ir_cut_filter(self, video_source_token: str) -> str:\n        body = f'''<timg:GetImagingSettings xmlns:timg=\"http://www.onvif.org/ver20/imaging/wsdl\">\n<timg:VideoSourceToken>{video_source_token}</timg:VideoSourceToken>\n</timg:GetImagingSettings>'''\n        response = self._soap(\n            self.base_url + \"/onvif/imaging\",\n            body,\n            \"http://www.onvif.org/ver20/imaging/wsdl/GetImagingSettings\",\n        )\n        root = ET.fromstring(response.content)\n        for element in root.iter():\n            if _localname(element.tag) == \"IrCutFilter\" and element.text:\n                value = element.text.strip().upper()\n                return {\"AUTO\": \"Auto\", \"ON\": \"Day\", \"OFF\": \"Night\"}.get(value, f\"Unknown ({value})\")\n        raise RuntimeError(f\"ONVIF GetImagingSettings returned no IrCutFilter for {video_source_token}\")\n\n    def set_ir_cut_filter(self, video_source_token: str, mode: str) -> str:\n        values = {\"auto\": \"AUTO\", \"day\": \"ON\", \"night\": \"OFF\"}\n        key = str(mode).strip().lower()\n        if key not in values:\n            raise ValueError(f\"Unsupported day/night mode: {mode}\")\n        ir_cut = values[key]\n        body = f'''<timg:SetImagingSettings xmlns:timg=\"http://www.onvif.org/ver20/imaging/wsdl\" xmlns:tt=\"http://www.onvif.org/ver10/schema\">\n<timg:VideoSourceToken>{video_source_token}</timg:VideoSourceToken>\n<timg:ImagingSettings><tt:IrCutFilter>{ir_cut}</tt:IrCutFilter></timg:ImagingSettings>\n<timg:ForcePersistence>true</timg:ForcePersistence>\n</timg:SetImagingSettings>'''\n        self._soap(\n            self.base_url + \"/onvif/imaging\",\n            body,\n            \"http://www.onvif.org/ver20/imaging/wsdl/SetImagingSettings\",\n        )\n        return {\"AUTO\": \"Auto\", \"ON\": \"Day\", \"OFF\": \"Night\"}[ir_cut]\n\n"""
repl(U, old, new)

old = '''            camera.setdefault("snapshot_channel", 2)\n        elif source_id == 3:\n            camera.setdefault("image_control_channel", 1)\n            camera.setdefault("snapshot_channel", 1)\n'''
new = '''            camera.setdefault("snapshot_channel", 2)\n            camera.setdefault("day_night_backend", "onvif_imaging")\n            camera.setdefault("video_source_token", "video_source2")\n        elif source_id == 3:\n            camera.setdefault("image_control_channel", 1)\n            camera.setdefault("snapshot_channel", 1)\n            camera.setdefault("day_night_backend", "onvif_imaging")\n            camera.setdefault("video_source_token", "video_source1")\n'''
repl(A, old, new)

old = '''            selected = channel\n            try:\n                private_exposure = source_id == 2\n                exposure = client.get_exposure(channel)\n                day_night = exposure.get("DayNight") if isinstance(exposure, dict) else None\n                cap_day_night = ((image_caps.get("Exposure") or {}).get("DayNight") or {}) if isinstance(image_caps, dict) else {}\n                supported = bool(cap_day_night.get("SupportDayNightCfg"))\n                if supported or (isinstance(day_night, dict) and "Mode" in day_night):\n                    found["day_night"] = True\n                    found["private_exposure"] = private_exposure\n                    found["day_night_mode"] = client.get_day_night_mode(channel, private=private_exposure)\n            except Exception as exc:\n                logging.debug("D%d day/night probe failed on channel %d: %s", source_id, channel, exc)\n\n'''
new = '''            selected = channel\n            camera_def = defs_by_id.get(source_id, {})\n            day_night_backend = str(camera_def.get("day_night_backend", "lapi")).strip().lower()\n            video_source_token = str(camera_def.get("video_source_token", "")).strip()\n            try:\n                if day_night_backend == "onvif_imaging" and video_source_token:\n                    found["day_night"] = True\n                    found["day_night_backend"] = "onvif_imaging"\n                    found["video_source_token"] = video_source_token\n                    found["day_night_mode"] = client.get_ir_cut_filter(video_source_token)\n                else:\n                    private_exposure = False\n                    exposure = client.get_exposure(channel)\n                    day_night = exposure.get("DayNight") if isinstance(exposure, dict) else None\n                    cap_day_night = ((image_caps.get("Exposure") or {}).get("DayNight") or {}) if isinstance(image_caps, dict) else {}\n                    supported = bool(cap_day_night.get("SupportDayNightCfg"))\n                    if supported or (isinstance(day_night, dict) and "Mode" in day_night):\n                        found["day_night"] = True\n                        found["day_night_backend"] = "lapi"\n                        found["private_exposure"] = private_exposure\n                        found["day_night_mode"] = client.get_day_night_mode(channel, private=private_exposure)\n            except Exception as exc:\n                logging.debug("D%d day/night probe failed on channel %d: %s", source_id, channel, exc)\n\n'''
repl(A, old, new)

old = '''                                private_exposure = bool(camera_caps[source_id].get("private_exposure"))\n                                mode = client.set_day_night_mode(channel, str(command.get("mode", "")), private=private_exposure)\n                                camera_caps[source_id]["day_night_mode"] = mode\n'''
new = '''                                caps = camera_caps[source_id]\n                                if caps.get("day_night_backend") == "onvif_imaging":\n                                    token = str(caps.get("video_source_token", "")).strip()\n                                    if not token:\n                                        raise RuntimeError(f"D{source_id} ONVIF Imaging day/night has no video source token")\n                                    mode = client.set_ir_cut_filter(token, str(command.get("mode", "")))\n                                else:\n                                    private_exposure = bool(caps.get("private_exposure"))\n                                    mode = client.set_day_night_mode(channel, str(command.get("mode", "")), private=private_exposure)\n                                camera_caps[source_id]["day_night_mode"] = mode\n'''
repl(A, old, new)

repl(C, "version: 1.5.12\n", "version: 1.5.13\n")
repl(A, '    options["addon_version"] = "1.5.12"\n', '    options["addon_version"] = "1.5.13"\n')
repl(A, '    logging.info("UNIVIEW CAMERA BRIDGE STARTING - version 1.5.12")\n', '    logging.info("UNIVIEW CAMERA BRIDGE STARTING - version 1.5.13")\n')

text = CH.read_text(encoding="utf-8")
entry = '''## 1.5.13\n\n- Use ONVIF Imaging `GetImagingSettings` / `SetImagingSettings` for day/night on the dual-lens IPC9312LFW-AF28-2X4, matching camera-side captures of the NVR/web UI.\n- Map D2 Front PTZ to `video_source2` and D3 Front Static to `video_source1`; `IrCutFilter` AUTO/ON/OFF maps to Auto/Day/Night.\n- Keep D2/D3 illumination on the existing LAPI `LampCtrl` path, which camera-side captures also confirm is the native control mechanism.\n- Leave standalone-camera day/night handling unchanged pending capture verification.\n\n'''
if "## 1.5.13\n" not in text:
    CH.write_text(entry + text, encoding="utf-8")
