from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / 'uniview_camera_bridge'
APP = ROOT / 'app.py'
CONFIG = ROOT / 'config.yaml'
UNIVIEW = ROOT / 'uniview.py'
CHANGELOG = ROOT / 'CHANGELOG.md'


def replace_once(path, old, new):
    text = path.read_text(encoding='utf-8')
    if old not in text:
        raise RuntimeError(f'Expected text not found in {path}: {old[:220]!r}')
    path.write_text(text.replace(old, new, 1), encoding='utf-8')

replace_once(APP,
'''def camera_definitions(options: dict[str, Any]) -> list[dict[str, Any]]:\n    return [c for c in (options.get("cameras") or []) if isinstance(c, dict) and c.get("enabled", True)]\n''',
'''def camera_definitions(options: dict[str, Any]) -> list[dict[str, Any]]:\n    result: list[dict[str, Any]] = []\n    for raw in (options.get("cameras") or []):\n        if not isinstance(raw, dict) or not raw.get("enabled", True):\n            continue\n        camera = dict(raw)\n        try:\n            source_id = int(camera.get("source_id"))\n        except (TypeError, ValueError):\n            result.append(camera)\n            continue\n\n        # Existing HA app options keep the saved `cameras:` list across app\n        # upgrades.  Fields added to config.yaml later therefore do not appear\n        # automatically in that saved list.  Apply model defaults at runtime so\n        # an installation predating snapshot_channel/image_control_channel still\n        # gets the known dual-lens mapping. Explicit user values still win.\n        if source_id == 2:\n            camera.setdefault("image_control_channel", 2)\n            camera.setdefault("snapshot_channel", 2)\n        elif source_id == 3:\n            camera.setdefault("image_control_channel", 1)\n            camera.setdefault("snapshot_channel", 1)\n        else:\n            camera.setdefault("snapshot_channel", 1)\n        result.append(camera)\n    return result\n''')

replace_once(UNIVIEW,
'''    def get_private_exposure(self, channel: int) -> dict[str, Any]:\n        response = self._request("GET", f"/LAPI/V1.0/Channels/{channel}/Image/Advanced/Private/Exposure/")\n        data = self._lapi_data(response)\n        if not isinstance(data, dict):\n            raise RuntimeError("Private exposure settings did not return an object")\n        return data\n\n    def get_day_night_mode(self, channel: int, private: bool = False) -> str:\n        exposure = self.get_private_exposure(channel) if private else self.get_exposure(channel)\n        day_night = exposure.get("DayNight") or {}\n        mode = int(day_night.get("Mode"))\n        return {0: "Auto", 1: "Day", 2: "Night"}.get(mode, f"Unknown ({mode})")\n\n    def set_day_night_mode(self, channel: int, mode: str, private: bool = False) -> str:\n        values = {"auto": 0, "day": 1, "night": 2}\n        key = str(mode).strip().lower()\n        if key not in values:\n            raise ValueError(f"Unsupported day/night mode: {mode}")\n        exposure = self.get_private_exposure(channel) if private else self.get_exposure(channel)\n        day_night = dict(exposure.get("DayNight") or {})\n        day_night["Mode"] = values[key]\n        exposure["DayNight"] = day_night\n        path = (\n            f"/LAPI/V1.0/Channels/{channel}/Image/Advanced/Private/Exposure/"\n            if private else f"/LAPI/V1.0/Channels/{channel}/Image/Advanced/Exposure"\n        )\n        response = self._request("PUT", path, json=exposure)\n        self._lapi_data(response)\n        return {0: "Auto", 1: "Day", 2: "Night"}[values[key]]\n''',
'''    def get_day_night_mode(self, channel: int, private: bool = False) -> str:\n        # The native D2 UI writes to the Private/Exposure endpoint, but that\n        # endpoint is not a reliable GET endpoint. Read current state from the\n        # ordinary Exposure resource and use Private/Exposure only for writes.\n        exposure = self.get_exposure(channel)\n        day_night = exposure.get("DayNight") or {}\n        raw_mode = day_night.get("Mode")\n        if raw_mode is None:\n            return "Unknown"\n        mode = int(raw_mode)\n        return {0: "Auto", 1: "Day", 2: "Night"}.get(mode, f"Unknown ({mode})")\n\n    def set_day_night_mode(self, channel: int, mode: str, private: bool = False) -> str:\n        values = {"auto": 0, "day": 1, "night": 2}\n        key = str(mode).strip().lower()\n        if key not in values:\n            raise ValueError(f"Unsupported day/night mode: {mode}")\n        # Seed the write body from the ordinary Exposure GET. The packet capture\n        # shows the D2 UI PUTting that exposure structure to Private/Exposure.\n        exposure = self.get_exposure(channel)\n        day_night = dict(exposure.get("DayNight") or {})\n        day_night["Mode"] = values[key]\n        exposure["DayNight"] = day_night\n        path = (\n            f"/LAPI/V1.0/Channels/{channel}/Image/Advanced/Private/Exposure/"\n            if private else f"/LAPI/V1.0/Channels/{channel}/Image/Advanced/Exposure"\n        )\n        response = self._request("PUT", path, json=exposure)\n        self._lapi_data(response)\n        return {0: "Auto", 1: "Day", 2: "Night"}[values[key]]\n''')

replace_once(APP,
'''            try:\n                private_exposure = source_id == 2\n                exposure = client.get_private_exposure(channel) if private_exposure else client.get_exposure(channel)\n                day_night = exposure.get("DayNight") if isinstance(exposure, dict) else None\n                if isinstance(day_night, dict) and "Mode" in day_night:\n                    found["day_night"] = True\n                    found["private_exposure"] = private_exposure\n                    found["day_night_mode"] = client.get_day_night_mode(channel, private=private_exposure)\n            except Exception as exc:\n                logging.debug("D%d day/night probe failed on channel %d: %s", source_id, channel, exc)\n''',
'''            try:\n                private_exposure = source_id == 2\n                exposure = client.get_exposure(channel)\n                day_night = exposure.get("DayNight") if isinstance(exposure, dict) else None\n                cap_day_night = ((image_caps.get("Exposure") or {}).get("DayNight") or {}) if isinstance(image_caps, dict) else {}\n                supported = bool(cap_day_night.get("SupportDayNightCfg"))\n                if supported or (isinstance(day_night, dict) and "Mode" in day_night):\n                    found["day_night"] = True\n                    found["private_exposure"] = private_exposure\n                    found["day_night_mode"] = client.get_day_night_mode(channel, private=private_exposure)\n            except Exception as exc:\n                logging.debug("D%d day/night probe failed on channel %d: %s", source_id, channel, exc)\n''')

replace_once(CONFIG, 'version: 1.5.4\n', 'version: 1.5.5\n')
replace_once(APP, '    options["addon_version"] = "1.5.4"\n', '    options["addon_version"] = "1.5.5"\n')
replace_once(APP, '    logging.info("UNIVIEW CAMERA BRIDGE STARTING - version 1.5.4")\n', '    logging.info("UNIVIEW CAMERA BRIDGE STARTING - version 1.5.5")\n')

text = CHANGELOG.read_text(encoding='utf-8')
entry = '''## 1.5.5\n\n- Apply D2/D3 dual-lens image/snapshot defaults at runtime as well as in `config.yaml`, so existing Home Assistant saved app options created before those fields were added do not silently fall back to snapshot channel 1.\n- Read D2 day/night state from the ordinary Exposure endpoint and reserve the packet-capture-proven Private/Exposure endpoint for writes; the private resource is not assumed to support GET.\n- Detect day/night support from ImageCapabilities as well as the current Exposure payload, preventing D2 from being disabled merely because a state-read probe is awkward.\n\n'''
if '## 1.5.5\n' not in text:
    # Keep newest entries first regardless of the historical misplaced heading.\n    CHANGELOG.write_text(entry + text, encoding='utf-8')
